### ISSUE TITLE
Error trying to parse file: Trailing comma before closing bracket

### ISSUE THREAD

**Issue by tmykkanen** [mangecoeur/AcademicMarkdown#6]
Here is the full text of the error:

Error trying to parse file: Trailing comma before closing bracket in ~/Library/Application Support/Sublime Text 2/Packages/AcademicMarkdown/Main.sublime-menu:29:25

This error is produced when AcademicMarkdown is opened in Sublime Text 2.0.2 Build 2221.

I resolved the error by removing the comma after the closing bracket on line 27.

**Comment by mangecoeur** [comment]
Thanks, I have not tested on ST 2 - I will integrate this fix
