### ISSUE TITLE
Critic Markup oversights

### ISSUE THREAD

**Issue by Cidxx** [mangecoeur/AcademicMarkdown#8]
Hello, and thanks for AM!

I've come across a little oversight in the code part regarding Critic Markup implementation.
In particular:

* in the AcademicMarkdown.tmLanguage the critic-highlight string should be `<string>\{==(.*?)[ \t]*(\[(.*?)\])?[ \t]*==\}</string>` instead of `<string>\{\{(.*?)[ \t]*(\[(.*?)\])?[ \t]*\}\}</string>`

* the AcademicMarkdownEditor.tmTheme is missing the definition for the Critic Markup substitution, so it'd be necessary to add:
```
        <dict>
            <key>name</key>
            <string>substitution</string>
            <key>scope</key>
            <string>criticmarkup.substitution</string>
            <key>settings</key>
            <dict>
                <key>fontStyle</key>
                <string>italic</string>
                <key>foreground</key>
                <string>#E78400</string>
            </dict>
        </dict>
```

Not being very familiar with GitHub workflow, I thought that posting the issues in this way might be the best. I thank you again for your wonderful plugin!

Cheers,

Syd

**Comment by mangecoeur** [comment]
Thanks for figuring out these out! I've made these changes and tagged a new release.
