### ISSUE TITLE
Syntax conflicts with spell-check

### ISSUE THREAD

**Issue by orschiro** [mangecoeur/AcademicMarkdown#9]
Hi @mangecoeur,

Do you have any idea why the AcademicMarkdown syntax conflicts with the spell-check?

![image](https://cloud.githubusercontent.com/assets/170947/6215044/503287ca-b5fd-11e4-8f14-0d2f59e1359a.png)

It does not happen with other syntaxes such as `Markdown Light`:

![image](https://cloud.githubusercontent.com/assets/170947/6215048/6649359a-b5fd-11e4-855f-aa4c2d4cf977.png)

Thankfully,

Robert

**Comment by mangecoeur** [comment]
It's possible that spell check is off be default (since, at least for me, it checks unfinished words while im typing which is annoying). You can turn it on/off by hitting F6. You can also edit the `spell_check` option in AcademicMarkdown user settings

**Comment by orschiro** [comment]
You misunderstood me. I would like to have spell-check enabled and 
wanted to pay attention to |AcademicMarkdown| conflicting with a 
correctly spelled word (|Approach|).

On 2015-02-16 17:04, mangecoeur wrote:

> It's possible that spell check is off be default (since, at least for 
> me, it checks unfinished words while im typing which is annoying). You 
> can turn it on/off by hitting F6. You can also edit the |spell_check| 
> option in AcademicMarkdown user settings
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mangecoeur/AcademicMarkdown/issues/9#issuecomment-74530787>.
>
​

-- 
mindfully present | passionate
simple design     | creative thinking
human hearted     | carpe diem

Co-Creator of @MindfulMeerkats
www.robert.orzanna.de
twitter.com/@orschiro

**Comment by mangecoeur** [comment]
Ok yeah that's super weird. It specifically happens to words in image reference. If you add a space after `Approach` it is correctly spell checked. 

However it seems to be a problem with MarkdownEditing - I re-use most of the functionality from that package and add support for citations, critic markup, and a few shortcuts. But I have absolutely no clue how syntax highlighting could affect the spellchecker :/ I suggest opening up an issue with MarkdownEditing (plus their hilghlight-fu is probably stronger than mine...)

**Comment by orschiro** [comment]
I will do and reference to here.

Thanks!

On 2015-02-16 17:12, mangecoeur wrote:
>
> Ok yeah that's super weird. It specifically happens to words in image 
> reference. If you add a space after |Approach| it is correctly spell 
> checked.
>
> However it seems to be a problem with MarkdownEditing - I re-use most 
> of the functionality from that package and add support for citations, 
> critic markup, and a few shortcuts. But I have absolutely no clue how 
> syntax highlighting could affect the spellchecker :/ I suggest opening 
> up an issue with MarkdownEditing (plus their hilghlight-fu is probably 
> stronger than mine...)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mangecoeur/AcademicMarkdown/issues/9#issuecomment-74532203>.
>

-- 
mindfully present | passionate
simple design     | creative thinking
human hearted     | carpe diem

Co-Creator of @MindfulMeerkats
www.robert.orzanna.de
twitter.com/@orschiro

**Comment by orschiro** [comment]
Opened issue: https://github.com/SublimeText-Markdown/MarkdownEditing/issues/231

**Comment by orschiro** [comment]
@mangecoeur 

The developer of MarkdownEditing does not think that the issue is related to his plugin. Can you comment on this?

Thanks!

**Comment by mangecoeur** [comment]
@orschiro It appears this has been fixed in SublimeText itself in the latest build:

http://www.sublimetext.com/3

> Tweaked handling of syntax definitions and unused captures, resolving an issue with spell checking in Markdown links

**Comment by orschiro** [comment]
Great news. Thanks for your update!
